module.exports = {
	NORMAL_RETURN:{CODE:0,MSG:''},
	DEFAULT_ERROR:{CODE:1000,MSG:'DEFAULT_ERROR'},
	SERVER_NO_HANDLER:{CODE:1001,MSG:'SERVER_NO_HANDLER'},
	PARAM_INVALID:{CODE:1002,MSG:'PARAM_INVALID'},
	DATA_DUPLICATED:{CODE:1003,MSG:'DATA_DUPLICATED'},

	MONGODB_SAVE_FAIL:{CODE:2001,MSG:'MONGODB_SAVE_FAIL'},

}