module.exports = {
	NORMAL_RETURN:{CODE:0,MSG:''},

	DEFAULT_ERROR:{CODE:1000,MSG:'DEFAULT_ERROR'},
	SERVER_NO_HANDLER:{CODE:1001,MSG:'SERVER_NO_HANDLER'},
	PARAM_INVALID:{CODE:1002,MSG:'PARAM_INVALID'},
	DATA_DUPLICATED:{CODE:1003,MSG:'DATA_DUPLICATED'},
	DATA_PROCESS_FAIL:{CODE:1004,MSG:'DATA_PROCESS_FAIL'},

	MONGODB_SAVE_FAIL:{CODE:2001,MSG:'MONGODB_SAVE_FAIL'},

	NAME_PWD_NOT_MATCH:{CODE:3001,MSG:'NAME_PWD_NOT_MATCH'},

	NO_JWT_HEADER:{CODE:4001,MSG:'NO_JWT_HEADER'},
	JWT_VALIDATE_FAIL:{CODE:4002,MSG:'JWT_VALIDATE_FAIL'},

	UPLOAD_ERR:{CODE:5001,MSG:'UPLOAD_ERR'},

}